"""Update Session table

Revision ID: 0834461a8ea3
Revises: 50e26225ff2c
Create Date: 2025-03-01 09:30:13.728539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0834461a8ea3'
down_revision: Union[str, None] = '50e26225ff2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'id',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
