"""Add unique_constraint to Session.user_id

Revision ID: d6d777ac326f
Revises: 0834461a8ea3
Create Date: 2025-03-01 10:16:28.229133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d777ac326f'
down_revision: Union[str, None] = '0834461a8ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_sessions_user_id'), 'sessions', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_sessions_user_id'), 'sessions', type_='unique')
    # ### end Alembic commands ###
